# Generated by Django 3.2.9 on 2021-11-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('banco_origen', models.CharField(max_length=100)),
                ('cuenta_origen', models.CharField(max_length=100)),
                ('banco_destino', models.CharField(max_length=100)),
                ('cuenta_destino', models.CharField(max_length=100)),
                ('monto', models.IntegerField()),
            ],
        ),
    ]
